---
- name: Install OpenJDK8
  apt:
    name: openjdk-8-jre-headless

- name: Create Service User
  user:
    name: '{{ cassandra_service_user }}'
    group: daemon
    comment: 'Cassandra service user'

- name: Check current Cassandra version
  stat:
    path: '{{ cassandra_install_dir }}'
  ignore_errors: true
  register: cassandra_symlink

- name: Install Cassandra
  when: >
    cassandra_symlink.stat.exists == false or
    cassandra_tarball_path != cassandra_symlink.stat.lnk_target
  block:
    - name: Download binary tarball
      get_url:
        url: '{{ cassandra_tarball_url }}'
        dest: '/tmp/{{ cassandra_tarball_file }}'
        checksum: 'sha256:{{ cassandra_tarball_sha256 }}'
        mode: 0644

    - name: Unpack binary tarball
      unarchive:
        src: '/tmp/{{ cassandra_tarball_file }}'
        dest: '/opt'
        creates: '/opt/{{ cassandra_tarball_name }}/bin/cassandra'
        owner: '{{ cassandra_service_user }}'
        group: 'adm'
        remote_src: yes

    - name: Symlink Cassandra version
      file:
        src: '{{ cassandra_tarball_path }}'
        dest: '{{ cassandra_install_dir }}'
        owner: '{{ cassandra_service_user }}'
        group: 'adm'
        state: 'link'
        force: true
      register: cassandra_installation
